import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, it, expect } from "vitest";
import { posts } from "../../data/blog-posts/registry";
import { imageSize } from "../image-size";
import {
  SITE_CARD,
  BLOG_POST_CARD,
  SOCIAL_DIR,
  blogPostCardFor,
} from "../social-cards";
import {
  SOCIAL_DIR as SCRIPT_SOCIAL_DIR,
  SOCIAL_HEIGHT,
  SOCIAL_WIDTH,
  socialTargets,
} from "../../../scripts/social.mjs";

/**
 * LinkedIn and Facebook only render the large hero card at or above
 * 1200x630; below that they fall back to a small square thumbnail, and X
 * center-crops anything squarer than ~1.91:1. Every page on this site sets
 * `twitter:card=summary_large_image`, so every share image has to clear the
 * bar or the card silently degrades — which is exactly what happened when the
 * homepage shipped a 556x556 headshot as its og:image.
 */
const MIN_WIDTH = 1200;
const MIN_HEIGHT = 630;

const ORIGIN = "https://pratik.pa.tel";

const publicImage = (path: string) =>
  imageSize(readFileSync(join(__dirname, "../../../public", path)));

/** SITE_CARD.url is absolute; the file it names lives under public/. */
const sitePath = SITE_CARD.url.slice(ORIGIN.length);

describe("social share images", () => {
  it("site card is at least 1200x630", () => {
    const { width, height } = publicImage(sitePath);
    expect(width).toBeGreaterThanOrEqual(MIN_WIDTH);
    expect(height).toBeGreaterThanOrEqual(MIN_HEIGHT);
  });

  // A declared og:image:width that disagrees with the file is worse than
  // declaring nothing: the scraper lays the card out from the lie, then
  // reflows or drops it once the real bytes arrive.
  it("site card matches its declared og:image dimensions", () => {
    expect(publicImage(sitePath)).toEqual({
      width: SITE_CARD.width,
      height: SITE_CARD.height,
    });
  });

  // Posts land via the unattended auto-merge routine, so an undersized image
  // would otherwise ship to production with nobody looking at the card.
  it.each(posts.map((p) => [p.slug, p.image] as const))(
    "post %s has a large-card image",
    (_slug, image) => {
      const { width, height } = publicImage(image);
      expect(width).toBeGreaterThanOrEqual(MIN_WIDTH);
      expect(height).toBeGreaterThanOrEqual(MIN_HEIGHT);
    },
  );

  // The card is cropped from the master at the master's own width, so a
  // master smaller than the card in either axis would be upscaled into a
  // card that claims detail it does not have. Same unattended-merge exposure
  // as above.
  it.each(posts.map((p) => [p.slug, p.image] as const))(
    "post %s has a master the card can be cropped from",
    (_slug, image) => {
      const { width, height } = publicImage(image);
      expect(width).toBeGreaterThanOrEqual(BLOG_POST_CARD.width);
      expect(height).toBeGreaterThanOrEqual(BLOG_POST_CARD.height);
    },
  );

  /**
   * The scraper card is a JPEG derived from the WebP master, because
   * LinkedIn's image spec does not list WebP. The derivation exists twice —
   * src/lib/social-cards.ts for the app bundle, scripts/social.mjs for the
   * Node generator — so these are what stop the meta tag from naming a file
   * the build never emitted.
   *
   * The emitted files themselves are gitignored and generated by the build,
   * which runs after `bun run test` in CI, so nothing here reads them.
   * e2e/social-card.spec.ts asserts the real bytes against the built site.
   */
  describe("post card stays in step with the generator", () => {
    it("agrees on the directory and the card size", () => {
      expect(SOCIAL_DIR).toBe(SCRIPT_SOCIAL_DIR);
      expect(BLOG_POST_CARD.width).toBe(SOCIAL_WIDTH);
      expect(BLOG_POST_CARD.height).toBe(SOCIAL_HEIGHT);
    });

    it("agrees on the path for every post", () => {
      for (const post of posts) {
        const card = blogPostCardFor(post.image);
        const [target] = socialTargets(post.image);

        expect(card).not.toBeNull();
        expect(target.publicPath).toBe(card!.path);
        expect(target.width).toBe(card!.width);
        expect(target.height).toBe(card!.height);
      }
    });

    // A card that kept the master's extension would be the WebP this change
    // exists to stop serving — and would also collide with the master's own
    // name if the directory ever flattened.
    it("emits a .jpg under the social directory", () => {
      for (const post of posts) {
        expect(blogPostCardFor(post.image)!.path).toMatch(
          new RegExp(`^${SOCIAL_DIR}/[^/]+\\.jpg$`),
        );
      }
    });

    // A remote hero is not the build's to re-encode. The post page falls back
    // to naming the master, and declares no dimensions for it.
    it("declines a hero the build does not own", () => {
      expect(blogPostCardFor("https://example.com/hero.webp")).toBeNull();
      expect(blogPostCardFor("/images/hero.gif")).toBeNull();
      expect(socialTargets("https://example.com/hero.webp")).toEqual([]);
    });
  });
});
